/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	initializationv1alpha1 "github.com/kcp-dev/init-agent/sdk/apis/initialization/v1alpha1"
)

// InitTargetClusterLister can list InitTargets across all workspaces, or scope down to a InitTargetLister for one workspace.
// All objects returned here must be treated as read-only.
type InitTargetClusterLister interface {
	// List lists all InitTargets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*initializationv1alpha1.InitTarget, err error)
	// Cluster returns a lister that can list and get InitTargets in one workspace.
	Cluster(clusterName logicalcluster.Name) InitTargetLister
	InitTargetClusterListerExpansion
}

type initTargetClusterLister struct {
	indexer cache.Indexer
}

// NewInitTargetClusterLister returns a new InitTargetClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewInitTargetClusterLister(indexer cache.Indexer) *initTargetClusterLister {
	return &initTargetClusterLister{indexer: indexer}
}

// List lists all InitTargets in the indexer across all workspaces.
func (s *initTargetClusterLister) List(selector labels.Selector) (ret []*initializationv1alpha1.InitTarget, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*initializationv1alpha1.InitTarget))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get InitTargets.
func (s *initTargetClusterLister) Cluster(clusterName logicalcluster.Name) InitTargetLister {
	return &initTargetLister{indexer: s.indexer, clusterName: clusterName}
}

// InitTargetLister can list all InitTargets, or get one in particular.
// All objects returned here must be treated as read-only.
type InitTargetLister interface {
	// List lists all InitTargets in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*initializationv1alpha1.InitTarget, err error)
	// Get retrieves the InitTarget from the indexer for a given workspace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*initializationv1alpha1.InitTarget, error)
	InitTargetListerExpansion
}

// initTargetLister can list all InitTargets inside a workspace.
type initTargetLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all InitTargets in the indexer for a workspace.
func (s *initTargetLister) List(selector labels.Selector) (ret []*initializationv1alpha1.InitTarget, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*initializationv1alpha1.InitTarget))
	})
	return ret, err
}

// Get retrieves the InitTarget from the indexer for a given workspace and name.
func (s *initTargetLister) Get(name string) (*initializationv1alpha1.InitTarget, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(initializationv1alpha1.Resource("inittargets"), name)
	}
	return obj.(*initializationv1alpha1.InitTarget), nil
}

// NewInitTargetLister returns a new InitTargetLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
func NewInitTargetLister(indexer cache.Indexer) *initTargetScopedLister {
	return &initTargetScopedLister{indexer: indexer}
}

// initTargetScopedLister can list all InitTargets inside a workspace.
type initTargetScopedLister struct {
	indexer cache.Indexer
}

// List lists all InitTargets in the indexer for a workspace.
func (s *initTargetScopedLister) List(selector labels.Selector) (ret []*initializationv1alpha1.InitTarget, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*initializationv1alpha1.InitTarget))
	})
	return ret, err
}

// Get retrieves the InitTarget from the indexer for a given workspace and name.
func (s *initTargetScopedLister) Get(name string) (*initializationv1alpha1.InitTarget, error) {
	key := name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(initializationv1alpha1.Resource("inittargets"), name)
	}
	return obj.(*initializationv1alpha1.InitTarget), nil
}
