/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	initializationv1alpha1 "github.com/kcp-dev/init-agent/sdk/apis/initialization/v1alpha1"
)

// InitTemplateClusterLister can list InitTemplates across all workspaces, or scope down to a InitTemplateLister for one workspace.
// All objects returned here must be treated as read-only.
type InitTemplateClusterLister interface {
	// List lists all InitTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*initializationv1alpha1.InitTemplate, err error)
	// Cluster returns a lister that can list and get InitTemplates in one workspace.
	Cluster(clusterName logicalcluster.Name) InitTemplateLister
	InitTemplateClusterListerExpansion
}

type initTemplateClusterLister struct {
	indexer cache.Indexer
}

// NewInitTemplateClusterLister returns a new InitTemplateClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewInitTemplateClusterLister(indexer cache.Indexer) *initTemplateClusterLister {
	return &initTemplateClusterLister{indexer: indexer}
}

// List lists all InitTemplates in the indexer across all workspaces.
func (s *initTemplateClusterLister) List(selector labels.Selector) (ret []*initializationv1alpha1.InitTemplate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*initializationv1alpha1.InitTemplate))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get InitTemplates.
func (s *initTemplateClusterLister) Cluster(clusterName logicalcluster.Name) InitTemplateLister {
	return &initTemplateLister{indexer: s.indexer, clusterName: clusterName}
}

// InitTemplateLister can list all InitTemplates, or get one in particular.
// All objects returned here must be treated as read-only.
type InitTemplateLister interface {
	// List lists all InitTemplates in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*initializationv1alpha1.InitTemplate, err error)
	// Get retrieves the InitTemplate from the indexer for a given workspace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*initializationv1alpha1.InitTemplate, error)
	InitTemplateListerExpansion
}

// initTemplateLister can list all InitTemplates inside a workspace.
type initTemplateLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all InitTemplates in the indexer for a workspace.
func (s *initTemplateLister) List(selector labels.Selector) (ret []*initializationv1alpha1.InitTemplate, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*initializationv1alpha1.InitTemplate))
	})
	return ret, err
}

// Get retrieves the InitTemplate from the indexer for a given workspace and name.
func (s *initTemplateLister) Get(name string) (*initializationv1alpha1.InitTemplate, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(initializationv1alpha1.Resource("inittemplates"), name)
	}
	return obj.(*initializationv1alpha1.InitTemplate), nil
}

// NewInitTemplateLister returns a new InitTemplateLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
func NewInitTemplateLister(indexer cache.Indexer) *initTemplateScopedLister {
	return &initTemplateScopedLister{indexer: indexer}
}

// initTemplateScopedLister can list all InitTemplates inside a workspace.
type initTemplateScopedLister struct {
	indexer cache.Indexer
}

// List lists all InitTemplates in the indexer for a workspace.
func (s *initTemplateScopedLister) List(selector labels.Selector) (ret []*initializationv1alpha1.InitTemplate, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*initializationv1alpha1.InitTemplate))
	})
	return ret, err
}

// Get retrieves the InitTemplate from the indexer for a given workspace and name.
func (s *initTemplateScopedLister) Get(name string) (*initializationv1alpha1.InitTemplate, error) {
	key := name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(initializationv1alpha1.Resource("inittemplates"), name)
	}
	return obj.(*initializationv1alpha1.InitTemplate), nil
}
