/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen-v0.33. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	initializationv1alpha1 "github.com/kcp-dev/init-agent/sdk/apis/initialization/v1alpha1"
	scheme "github.com/kcp-dev/init-agent/sdk/clientset/versioned/scheme"
)

// InitTemplatesGetter has a method to return a InitTemplateInterface.
// A group's client should implement this interface.
type InitTemplatesGetter interface {
	InitTemplates() InitTemplateInterface
}

// InitTemplateInterface has methods to work with InitTemplate resources.
type InitTemplateInterface interface {
	Create(ctx context.Context, initTemplate *initializationv1alpha1.InitTemplate, opts v1.CreateOptions) (*initializationv1alpha1.InitTemplate, error)
	Update(ctx context.Context, initTemplate *initializationv1alpha1.InitTemplate, opts v1.UpdateOptions) (*initializationv1alpha1.InitTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*initializationv1alpha1.InitTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*initializationv1alpha1.InitTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *initializationv1alpha1.InitTemplate, err error)
	InitTemplateExpansion
}

// initTemplates implements InitTemplateInterface
type initTemplates struct {
	*gentype.ClientWithList[*initializationv1alpha1.InitTemplate, *initializationv1alpha1.InitTemplateList]
}

// newInitTemplates returns a InitTemplates
func newInitTemplates(c *InitializationV1alpha1Client) *initTemplates {
	return &initTemplates{
		gentype.NewClientWithList[*initializationv1alpha1.InitTemplate, *initializationv1alpha1.InitTemplateList](
			"inittemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *initializationv1alpha1.InitTemplate { return &initializationv1alpha1.InitTemplate{} },
			func() *initializationv1alpha1.InitTemplateList { return &initializationv1alpha1.InitTemplateList{} },
		),
	}
}
