/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen-v0.33. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	initializationv1alpha1 "github.com/kcp-dev/init-agent/sdk/apis/initialization/v1alpha1"
	scheme "github.com/kcp-dev/init-agent/sdk/clientset/versioned/scheme"
)

// InitTargetsGetter has a method to return a InitTargetInterface.
// A group's client should implement this interface.
type InitTargetsGetter interface {
	InitTargets() InitTargetInterface
}

// InitTargetInterface has methods to work with InitTarget resources.
type InitTargetInterface interface {
	Create(ctx context.Context, initTarget *initializationv1alpha1.InitTarget, opts v1.CreateOptions) (*initializationv1alpha1.InitTarget, error)
	Update(ctx context.Context, initTarget *initializationv1alpha1.InitTarget, opts v1.UpdateOptions) (*initializationv1alpha1.InitTarget, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*initializationv1alpha1.InitTarget, error)
	List(ctx context.Context, opts v1.ListOptions) (*initializationv1alpha1.InitTargetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *initializationv1alpha1.InitTarget, err error)
	InitTargetExpansion
}

// initTargets implements InitTargetInterface
type initTargets struct {
	*gentype.ClientWithList[*initializationv1alpha1.InitTarget, *initializationv1alpha1.InitTargetList]
}

// newInitTargets returns a InitTargets
func newInitTargets(c *InitializationV1alpha1Client) *initTargets {
	return &initTargets{
		gentype.NewClientWithList[*initializationv1alpha1.InitTarget, *initializationv1alpha1.InitTargetList](
			"inittargets",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *initializationv1alpha1.InitTarget { return &initializationv1alpha1.InitTarget{} },
			func() *initializationv1alpha1.InitTargetList { return &initializationv1alpha1.InitTargetList{} },
		),
	}
}
