/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	initializationv1alpha1 "github.com/kcp-dev/init-agent/sdk/apis/initialization/v1alpha1"
	scopedclientset "github.com/kcp-dev/init-agent/sdk/clientset/versioned"
	clientset "github.com/kcp-dev/init-agent/sdk/clientset/versioned/cluster"
	"github.com/kcp-dev/init-agent/sdk/informers/externalversions/internalinterfaces"
	initializationv1alpha1listers "github.com/kcp-dev/init-agent/sdk/listers/initialization/v1alpha1"
)

// InitTemplateClusterInformer provides access to a shared informer and lister for
// InitTemplates.
type InitTemplateClusterInformer interface {
	Cluster(logicalcluster.Name) InitTemplateInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() initializationv1alpha1listers.InitTemplateClusterLister
}

type initTemplateClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewInitTemplateClusterInformer constructs a new informer for InitTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInitTemplateClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredInitTemplateClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredInitTemplateClusterInformer constructs a new informer for InitTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInitTemplateClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InitializationV1alpha1().InitTemplates().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InitializationV1alpha1().InitTemplates().Watch(context.TODO(), options)
			},
		},
		&initializationv1alpha1.InitTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *initTemplateClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredInitTemplateClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName: kcpcache.ClusterIndexFunc,
	},
		f.tweakListOptions,
	)
}

func (f *initTemplateClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&initializationv1alpha1.InitTemplate{}, f.defaultInformer)
}

func (f *initTemplateClusterInformer) Lister() initializationv1alpha1listers.InitTemplateClusterLister {
	return initializationv1alpha1listers.NewInitTemplateClusterLister(f.Informer().GetIndexer())
}

// InitTemplateInformer provides access to a shared informer and lister for
// InitTemplates.
type InitTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() initializationv1alpha1listers.InitTemplateLister
}

func (f *initTemplateClusterInformer) Cluster(clusterName logicalcluster.Name) InitTemplateInformer {
	return &initTemplateInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type initTemplateInformer struct {
	informer cache.SharedIndexInformer
	lister   initializationv1alpha1listers.InitTemplateLister
}

func (f *initTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *initTemplateInformer) Lister() initializationv1alpha1listers.InitTemplateLister {
	return f.lister
}

type initTemplateScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

func (f *initTemplateScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&initializationv1alpha1.InitTemplate{}, f.defaultInformer)
}

func (f *initTemplateScopedInformer) Lister() initializationv1alpha1listers.InitTemplateLister {
	return initializationv1alpha1listers.NewInitTemplateLister(f.Informer().GetIndexer())
}

// NewInitTemplateInformer constructs a new informer for InitTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInitTemplateInformer(client scopedclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInitTemplateInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredInitTemplateInformer constructs a new informer for InitTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInitTemplateInformer(client scopedclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InitializationV1alpha1().InitTemplates().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InitializationV1alpha1().InitTemplates().Watch(context.TODO(), options)
			},
		},
		&initializationv1alpha1.InitTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *initTemplateScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInitTemplateInformer(client, resyncPeriod, cache.Indexers{}, f.tweakListOptions)
}
