/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"github.com/kcp-dev/init-agent/sdk/informers/externalversions/internalinterfaces"
)

type ClusterInterface interface {
	// InitTargets returns a InitTargetClusterInformer
	InitTargets() InitTargetClusterInformer
	// InitTemplates returns a InitTemplateClusterInformer
	InitTemplates() InitTemplateClusterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new ClusterInterface.
func New(f internalinterfaces.SharedInformerFactory, tweakListOptions internalinterfaces.TweakListOptionsFunc) ClusterInterface {
	return &version{factory: f, tweakListOptions: tweakListOptions}
}

// InitTargets returns a InitTargetClusterInformer
func (v *version) InitTargets() InitTargetClusterInformer {
	return &initTargetClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// InitTemplates returns a InitTemplateClusterInformer
func (v *version) InitTemplates() InitTemplateClusterInformer {
	return &initTemplateClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

type Interface interface {
	// InitTargets returns a InitTargetInformer
	InitTargets() InitTargetInformer
	// InitTemplates returns a InitTemplateInformer
	InitTemplates() InitTemplateInformer
}

type scopedVersion struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// New returns a new ClusterInterface.
func NewScoped(f internalinterfaces.SharedScopedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &scopedVersion{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// InitTargets returns a InitTargetInformer
func (v *scopedVersion) InitTargets() InitTargetInformer {
	return &initTargetScopedInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// InitTemplates returns a InitTemplateInformer
func (v *scopedVersion) InitTemplates() InitTemplateInformer {
	return &initTemplateScopedInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
