/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.33. DO NOT EDIT.

package v1alpha1

// InitTargetSpecApplyConfiguration represents a declarative configuration of the InitTargetSpec type for use
// with apply.
type InitTargetSpecApplyConfiguration struct {
	WorkspaceTypeReference *WorkspaceTypeReferenceApplyConfiguration `json:"workspaceTypeRef,omitempty"`
	Sources                []InitSourceApplyConfiguration            `json:"sources,omitempty"`
}

// InitTargetSpecApplyConfiguration constructs a declarative configuration of the InitTargetSpec type for use with
// apply.
func InitTargetSpec() *InitTargetSpecApplyConfiguration {
	return &InitTargetSpecApplyConfiguration{}
}

// WithWorkspaceTypeReference sets the WorkspaceTypeReference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkspaceTypeReference field is set to the value of the last call.
func (b *InitTargetSpecApplyConfiguration) WithWorkspaceTypeReference(value *WorkspaceTypeReferenceApplyConfiguration) *InitTargetSpecApplyConfiguration {
	b.WorkspaceTypeReference = value
	return b
}

// WithSources adds the given value to the Sources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sources field.
func (b *InitTargetSpecApplyConfiguration) WithSources(values ...*InitSourceApplyConfiguration) *InitTargetSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSources")
		}
		b.Sources = append(b.Sources, *values[i])
	}
	return b
}
