/*
Copyright The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"

	initializationv1alpha1 "github.com/kcp-dev/init-agent/sdk/apis/initialization/v1alpha1"
	initializationv1alpha1client "github.com/kcp-dev/init-agent/sdk/clientset/versioned/typed/initialization/v1alpha1"
)

// InitTargetsClusterGetter has a method to return a InitTargetClusterInterface.
// A group's cluster client should implement this interface.
type InitTargetsClusterGetter interface {
	InitTargets() InitTargetClusterInterface
}

// InitTargetClusterInterface can operate on InitTargets across all clusters,
// or scope down to one cluster and return a initializationv1alpha1client.InitTargetInterface.
type InitTargetClusterInterface interface {
	Cluster(logicalcluster.Path) initializationv1alpha1client.InitTargetInterface
	List(ctx context.Context, opts metav1.ListOptions) (*initializationv1alpha1.InitTargetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type initTargetsClusterInterface struct {
	clientCache kcpclient.Cache[*initializationv1alpha1client.InitializationV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *initTargetsClusterInterface) Cluster(clusterPath logicalcluster.Path) initializationv1alpha1client.InitTargetInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return c.clientCache.ClusterOrDie(clusterPath).InitTargets()
}

// List returns the entire collection of all InitTargets across all clusters.
func (c *initTargetsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*initializationv1alpha1.InitTargetList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).InitTargets().List(ctx, opts)
}

// Watch begins to watch all InitTargets across all clusters.
func (c *initTargetsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).InitTargets().Watch(ctx, opts)
}
